replicaCount: 3

image:
  repository: localhost:5000/cert-manager-istio-csr
  tag: v0.2.1
  pullPolicy: Always

service:
  port: 443
  type: NodePort
  nodePort: 30443

app:
  logLevel: 5

  certmanager:
    namespace: istio-system
    preserveCertificateRequests: true
    issuer:
      group: cert-manager.io
      kind: Issuer
      name: istio-ca

  tls:
    trustDomain: foo.bar
    certificateDuration: 20s
    certificateDNSNames:
    # Name used by the e2e client
    - istio-csr.cert-manager.svc
    # Name used within the demo cluster
    - cert-manager-istio-csr.cert-manager.svc

  server:
    maxCertificateDuration: 5m
    serving:
      address: 0.0.0.0
      port: 6443


  controller:
    rootCAConfigMapName: istio-ca-root-cert


resources: {}
