apiVersion: v1

name: cert-manager-istio-csr
type: application
description: A Helm chart for istio-csr

home: https://github.com/cert-manager/istio-csr
maintainers:
- name: joshvanl
  email: joshua.vanleeuwen@jetstack.io
  url: https://cert-manager.io
sources:
- https://github.com/cert-manager/istio-csr

appVersion: v0.3.0
version: v0.3.0
